### ISSUE TITLE
Add support for cflinuxfs4

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/cf-deployment#989]
### What is this issue about?

The [cflinuxfs4](https://github.com/cloudfoundry/cflinuxfs4) stack is now available, based on Ubuntu 22.04 "Jammy Jellyfish". Application developers will need to move to this stack before cflinuxfs3 leaves support.

Related proposal: https://docs.google.com/document/d/1dJAJBw8gI0Kapxvxhy73-Z63avs7tGE-GqAM-DOBaPM/edit

cflinuxfs4 stack
- [x] [cflinuxfs4-release](https://github.com/cloudfoundry/cflinuxfs4-release)

cflinux4 support for buildpacks shipped with cf-deployment (according to release notes):
- [x] [java-buildpack](https://github.com/cloudfoundry/java-buildpack), since v4.52
- [x] [dotnet-core-buildpack](https://github.com/cloudfoundry/dotnet-core-buildpack), since v2.4.0
- [x] [nodejs-buildpack](https://github.com/cloudfoundry/nodejs-buildpack), since v1.7.74
- [x] [python-buildpack](https://github.com/cloudfoundry/python-buildpack), since v1.8.0
- [x] [go-buildpack](https://github.com/cloudfoundry/go-buildpack), v1.10.0 has a packaging issue, v1.10.1 works: https://github.com/cloudfoundry/cf-deployment/pull/1022
- [x] [ruby-buildpack](https://github.com/cloudfoundry/ruby-buildpack), since v1.9.0
- [x] [staticfile-buildpack](https://github.com/cloudfoundry/staticfile-buildpack) -> https://github.com/cloudfoundry/staticfile-buildpack-release/issues/1
- [x] [php-buildpack](https://github.com/cloudfoundry/php-buildpack) -> https://github.com/cloudfoundry/php-buildpack-release/issues/2
- [x] [nginx-buildpack](https://github.com/cloudfoundry/nginx-buildpack) -> https://github.com/cloudfoundry/nginx-buildpack-release/issues/3
- [x] [r-buildpack](https://github.com/cloudfoundry/r-buildpack) -> https://github.com/cloudfoundry/r-buildpack-release/issues/2
- [x] [binary-buildpack](https://github.com/cloudfoundry/binary-buildpack), since v1.1.0

Integration of cflinuxfs4 into cf-deployment
- [x] experimental ops file to ship cflinuxfs4 and supported buildpacks as opt-in, #1008 
- [x] experimental ops file to make cflinuxfs4 default stack, #1011 
- [x] run CATS against cflinuxfs4 (either in experimental-hermione or in a separate pipeline), #1015, [cf-acceptance-tests #642](https://github.com/cloudfoundry/cf-acceptance-tests/issues/642) -> https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4
- [x] promote cflinuxfs4 ops files (could be skipped if we integrate the ops files directly into cf-deployment.yml)
- [x] rollout step 1: https://github.com/cloudfoundry/cf-deployment/issues/1047
- [x] rollout step 2: https://github.com/cloudfoundry/cf-deployment/issues/1048
- [x] rollout step 3: https://github.com/cloudfoundry/cf-deployment/issues/1093

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

Latest

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

N/A

### Please provide output that helps describe the issue:

N/A

### What IaaS is this issue occurring on?

N/A

### Is there anything else unique or special about your setup?

N/A

**Comment by stephanme** [comment]
Added overview of cflinuxfs4 support and integration steps into cf-deployment (as discussed in WG meeting 22-11-10).

**Comment by jochenehret** [comment]
All done, closing! Thanks to everyone who contributed!
